server:
  port: 10106

spring:
  application:
    name: monitor-springboot-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    deserialization:
     #允许对象忽略json中不存在的属性
     fail_on_unknown_properties: false
  # rest 链路前缀
  data:
    rest:
      base-path: /api

  sleuth:
    sampler:
      probability: 1.0 #采样比例
    enabled: true
    http:
      legacy:
        enabled: true
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#这样才能访问 /actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有端口
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always #展示健康信息的细节
logging:
  level:
    com.ynding.cloud.monitor: debug
    org.hibernate.SQL: WARN
    org.springframework.web: WARN